{ pkgs, ...}:
{
  service.tlp = {
    enable = true;
    settings = {
CPU_DRIVER_OPMODE_ON_AC="passive";
CPU_DRIVER_OPMODE_ON_BAT="active";

CPU_SCALING_GOVERNOR_ON_AC="ondemand";
CPU_SCALING_GOVERNOR_ON_BAT="powersave";

CPU_ENERGY_PERF_POLICY_ON_AC="default";
CPU_ENERGY_PERF_POLICY_ON_BAT="balance-power";

CPU_MIN_PERF_ON_AC=12;
CPU_MAX_PERF_ON_AC=100;
CPU_MIN_PERF_ON_BAT=2;
CPU_MAX_PERF_ON_BAT=42;

CPU_BOOST_ON_AC=1;
CPU_BOOST_ON_BAT=0;

CPU_HWP_DYN_BOOST_ON_AC=1;
CPU_HWP_DYN_BOOST_ON_BAT=0;

PLATFORM_PROFILE_ON_AC="performance";
PLATFORM_PROFILE_ON_BAT="low-power";

MEM_SLEEP_ON_AC="s2idle";
MEM_SLEEP_ON_BAT="s2idle";

INTEL_GPU_MIN_FREQ_ON_AC=150;
INTEL_GPU_MIN_FREQ_ON_BAT=100;
INTEL_GPU_MAX_FREQ_ON_AC=950;
INTEL_GPU_MAX_FREQ_ON_BAT=600;
INTEL_GPU_BOOST_FREQ_ON_AC=1100;
INTEL_GPU_BOOST_FREQ_ON_BAT=700;

PCIE_ASPM_ON_AC="default";
PCIE_ASPM_ON_BAT="powersupersave";

DEVICES_TO_DISABLE_ON_STARTUP="bluetooth nfc wwan";
DEVICES_TO_ENABLE_ON_STARTUP="wifi";
DEVICES_TO_DISABLE_ON_SHUTDOWN="bluetooth nfc wifi wwan";

DEVICES_TO_ENABLE_ON_AC="nfc wwan";
DEVICES_TO_DISABLE_ON_BAT="nfc wwan";
DEVICES_TO_DISABLE_ON_BAT_NOT_IN_USE="bluetooth nfc wifi wwan";

RESTORE_THRESHOLDS_ON_BAT=0;
    };
  };
}
